name: Fast-forward dev branch

on:
  push:
    branches:
      - main

jobs:
  merge_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Fetch main branch
        run: git fetch origin main

      - name: Attempt fast-forward merge
        run: git merge --ff-only origin/main development || echo "No fast-forward possible."

      - name: Push changes
        run: git push origin dev
