name: Fast-forward dev branch

on:
  push:
    branches:
      - main

jobs:
  merge_to_dev:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Attempt fast-forward merge
        run: git merge --ff-only origin/main || echo "No fast-forward possible."

      - name: Push changes
        run: git push
